config/routes.rb
Rails.application.routes.draw do

  get 'sections/new'

  root 'books#index'

  resources :books do 
    resources :chapters do
      resources :sections
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  validates :title, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :sections, dependent: :destroy
  validates :title, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: [:show, :edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def index
    @books = Book.all
  end

  def show
  end

  def edit  
  end

  def update
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :description)
    end

    def fetch_book
      @book = Book.find(params[:id])
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only: [:show, :edit, :update, :destroy]

  def new
    @chapter = @book.chapters.new
  end

  def create
    @chapter = @book.chapters.new(chapter_params)
    if @chapter.save
      redirect_to book_chapters_path(@book, @chapter)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @chapter.update_attributes(chapter_params)
      redirect_to book_chapters_path(@book, @chapter)
    else
      render :edit
    end
  end

  def index
    @chapters = @book.chapters.all
  end

  def destroy
    @chapter.destroy
    redirect_to book_chapters_path(@book)
  end

  private

    def fetch_book
      @book = Book.find(params[:book_id])
    end

    def fetch_chapter
      @chapter = @book.chapters.find(params[:id])
    end

    def chapter_params
      params.require(:chapter).permit(:title)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter
  before_action :fetch_section, only: [:show, :edit, :update, :destroy]

  def new
    @section = @chapter.sections.new
  end

  def create
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to book_chapter_sections_path(@book, @chapter)
    else
      render :new
    end
  end

  def index
    @sections = @chapter.sections.all
  end

  def show
  end

  def edit
  end

  def update
    if @section.update_attributes(section_params)
      redirect_to book_chapter_sections_path(@book, @chapter)
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to book_chapter_sections_path(@book, @chapter)
  end

  private

    def fetch_book
      @book = Book.find(params[:book_id])
    end

    def fetch_chapter
      @chapter = @book.chapters.find(params[:chapter_id])
    end

    def fetch_section
      @section = @chapter.sections.find(params[:id])
    end

    def section_params 
      params.require(:section).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/books/edit.html.erb
<h1>Edit the Book: <%= @book.title %></h1>
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Edit Book", class: "btn btn-primary" %>
<% end %>

app/views/books/index.html.erb
<h1>Your Books</h1>
<% @books.each do |book| %>
  <h2><%= link_to "#{book.title}", book_path(book) %></h2>
<% end %>
<%= link_to "Create a new Book", new_book_path, class: "btn btn-primary" %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Add Book", class: "btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4><%= @book.description %></h4>
<% @book.chapters.each do |chapter| %>
  <h3><%= link_to chapter.title, book_chapter_path(@book, chapter) %></h3>
<% end %>
<%= link_to "Edit Book", edit_book_path(@book), class: "btn btn-primary" %>
<%= link_to "Delete Book", book_path(@book), method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure you want to delete this book and all its related chapters.' } %>
<%= link_to "Add Chapter", new_book_chapter_path(@book), class: "btn btn-primary" %>

app/views/chapters/edit.html.erb
<h1><%= @book.title %></h1>
<h3>Edit the Chapter: <%= @chapter.title %></h3>
<%= simple_form_for [@book, @chapter]  do |f| %>
  <%= f.input :title %>
  <%= f.submit "Edit Chapter", class: "btn btn-primary" %>
<% end %>

app/views/chapters/index.html.erb
<h1><%= @book.title %></h1>  
<% @chapters.each do |chapter| %>
  <h3><%= link_to chapter.title, book_chapter_path(@book, chapter) %></h3>  
<% end %>
<%= link_to "Add Chapter", new_book_chapter_path(@book), class: "btn btn-primary" %>

app/views/chapters/new.html.erb
<h1>Create a new chapter for <%= @book.title %></h1>
<%= simple_form_for [@book, @chapter] do |f| %>
  <%= f.input :title %>
  <%= f.submit "Add Chapter", class:"btn btn-primary" %>
<% end %> 

app/views/chapters/show.html.erb
<h1><%= @book.title %></h1>
<h3><%= @chapter.title %></h3>
<%= link_to "Edit Chapter", edit_book_chapter_path(@book, @chapter), class: "btn btn-primary" %>
<%= link_to "Delete Chapter", book_chapter_path(@book, @chapter), method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure you want to delete this chapter.' } %>
<%= link_to "Add Section", new_book_chapter_section_path(@book, @chapter),class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/sections/edit.html.erb
<h1><%= @book.title %></h1>
<h2><%= @chapter.title %></h2>
<h3>Edit the Section: <%= @section.title %></h3>
<%= simple_form_for [@book, @chapter, @section]  do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit "Edit Section", class: "btn btn-primary" %>
<% end %>

app/views/sections/index.html.erb
<h1><%= link_to @book.title, book_path(@book) %></h1>
<h2><%= link_to @chapter.title, book_chapter_path(@book, @chapter) %></h2>
<% @sections.each do |section| %>
  <h4><%= link_to section.title, book_chapter_section_path(@book, @chapter, section) %>
  </h4>  
<% end %>
<%= link_to "Add Section", new_book_chapter_section_path(@book, @chapter), class: "btn btn-primary" %>

app/views/sections/new.html.erb
<h2>Please add a section to the book : <%= @book.title %>, in the chapter <%= @chapter.title %>.</h2>
<%= simple_form_for [@book, @chapter, @section] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit "Add Section", class:"btn btn-primary" %>
<% end %>

app/views/sections/show.html.erb
<h1><%= link_to @book.title, book_path(@book) %></h1>
<h2><%= link_to @chapter.title, book_chapter_path(@book, @chapter) %></h2>
<h4><%= @section.title %></h4>
<p><%= @section.content %></p>
<%= link_to "Edit Section", edit_book_chapter_section_path(@book, @chapter, @section), class: "btn btn-primary" %>
<%= link_to "Delete Section", book_chapter_section_path(@book, @chapter, @section), method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure you want to delete this section.' } %>